apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: weather-app
type: application
version: 0.1.0
dependencies:
  - name: value
    repository: https://github.com/ArielDomchik/Personal-space
    version: 1.0.0
