apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "a82fa42cee85a44bf93890b300ffdd22-1094996862.us-east-1.elb.amazonaws.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: weather-app
            port:
              number: 80
  - host: "a82fa42cee85a44bf93890b300ffdd22-1094996862.us-east-1.elb.amazonaws.com"
    http:
      paths:
      - pathType: Prefix
        path: "/solitaire"
        backend:
          service:
            name: solitaire
            port:
              number: 80
