apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-app-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "{{ .Values.awsElasticBlockStore.volumeID }}"
    fsType: "{{ .Values.awsElasticBlockStore.fsType }}"
  storageClassName: {{ .Values.storageClassName }}
