apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.storageClassName }}
